name: xcube-sh
channels:
  - conda-forge
  - defaults
dependencies:

  # Required
  # - xcube >=0.4.0
  - oauthlib >=3.0
  - pip >=19.1

  - pip:
    # Required
    - requests_oauthlib

  # testing
  - flake8
  - pytest
  - pytest-cov
